### ISSUE TITLE
controlNet has stopped working for me?

### ISSUE THREAD

**Issue by JeffreyBull76** [Mikubill/sd-webui-controlnet#252]
I did a fresh install a few days back all worked perfectly, was happily generating images. Tried a depth map generation and it threw this error.

`Loading preprocessor: canny, model: diff_control_sd15_canny_fp16 [ea6e3b9c]
Loaded state_dict from [C:\SD_NewInstall\stable-diffusion-webui\extensions\sd-webui-controlnet\models\diff_control_sd15_canny_fp16.safetensors]
Offset cloned: 298 values
ControlNet model diff_control_sd15_canny_fp16 [ea6e3b9c] loaded.
  0%|                                                                                           | 0/20 [00:03<?, ?it/s]
Error completing request
Arguments: ('task(yqjp37scjs7401l)', "persons face screaming, 35mm lens, I can't believe how beautiful this is, oddly satisfying, key visual, hdr, 8k, rim lighting, fashion photography, extremely detailed, photo realism, modelling shot, stunning, gorgeous, (RTX, FXAA, TXAA, sharpen, SFX, SSAO, post-processing:1.5), by WeTa FX, industrial light & magic", '(((asian))), deformed, bad anatomy, disfigured, poorly drawn face, mutation, mutated, extra limb, ugly, disgusting, poorly drawn hands, missing limb, floating limbs, disconnected limbs, malformed hands, blurry, ((((mutated hands and fingers)))), watermark, watermarked, oversaturated, censored, distorted hands, amputation, missing hands, obese, doubled face, double hands, sepia,', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, True, 'canny', 'diff_control_sd15_canny_fp16 [ea6e3b9c]', 1, {'image': array([[[164, 164, 162],
        [164, 164, 162],
        [164, 164, 162],
        ...,
        [172, 173, 175],
        [172, 173, 175],
        [172, 173, 175]],

       [[164, 164, 162],
        [164, 164, 162],
        [164, 164, 162],
        ...,
        [172, 173, 175],
        [172, 173, 175],
        [172, 173, 175]],

       [[164, 164, 162],
        [164, 164, 162],
        [164, 164, 162],
        ...,
        [172, 173, 175],
        [172, 173, 175],
        [172, 173, 175]],

       ...,

       [[160, 160, 160],
        [160, 160, 160],
        [160, 160, 160],
        ...,
        [183, 184, 189],
        [183, 184, 189],
        [183, 184, 189]],

       [[159, 159, 159],
        [159, 159, 159],
        [159, 159, 159],
        ...,
        [183, 184, 189],
        [183, 184, 189],
        [183, 184, 189]],

       [[159, 159, 159],
        [159, 159, 159],
        [159, 159, 159],
        ...,
        [183, 184, 189],
        [183, 184, 189],
        [183, 184, 189]]], dtype=uint8), 'mask': array([[[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       ...,

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]]], dtype=uint8)}, False, 'Just Resize', False, True, 512, 100, 200, 1, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, False, 'Not set', True, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', False, 'None', '', 5, 24, 12.5, 1000, 'DDIM', 0, 64, 64, '', 64, 7.5, 0.42, 'DDIM', 64, 64, 1, 0, 92, True, True, True, False, False, False, 'midas_v21_small') {}
Traceback (most recent call last):
  File "C:\SD_NewInstall\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\SD_NewInstall\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\SD_NewInstall\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\SD_NewInstall\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\SD_NewInstall\stable-diffusion-webui\modules\processing.py", line 632, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\SD_NewInstall\stable-diffusion-webui\modules\processing.py", line 832, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\SD_NewInstall\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 349, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\SD_NewInstall\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 225, in launch_sampling
    return func()
  File "C:\SD_NewInstall\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 349, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\SD_NewInstall\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\SD_NewInstall\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\SD_NewInstall\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\SD_NewInstall\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 123, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": [cond_in[a:b]], "c_concat": [image_cond_in[a:b]]})
  File "C:\SD_NewInstall\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\SD_NewInstall\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\SD_NewInstall\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\SD_NewInstall\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\SD_NewInstall\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\SD_NewInstall\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\SD_NewInstall\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "C:\SD_NewInstall\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\SD_NewInstall\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\SD_NewInstall\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 185, in forward2
    return forward(*args, **kwargs)
  File "C:\SD_NewInstall\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 143, in forward
    control = outer.control_model(x=x, hint=outer.hint_cond, timesteps=timesteps, context=context)
  File "C:\SD_NewInstall\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\SD_NewInstall\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 479, in forward
    h = module(h, emb, context)
  File "C:\SD_NewInstall\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\SD_NewInstall\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "C:\SD_NewInstall\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\SD_NewInstall\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 324, in forward
    x = block(x, context=context[i])
  File "C:\SD_NewInstall\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\SD_NewInstall\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 259, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "C:\SD_NewInstall\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 114, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "C:\SD_NewInstall\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 129, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "C:\SD_NewInstall\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 264, in _forward
    x = self.ff(self.norm3(x)) + x
  File "C:\SD_NewInstall\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\SD_NewInstall\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 73, in forward
    return self.net(x)
  File "C:\SD_NewInstall\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\SD_NewInstall\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "C:\SD_NewInstall\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\SD_NewInstall\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 53, in forward
    return x * F.gelu(gate)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 4.68 GiB already allocated; 0 bytes free; 4.76 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

After it throws this error it then refused to work. I can restart automatic 1111 and it generates other images fine but as soon as I try to use controlNet it just crashes. Very odd as I was using it fine then it seems to have just stopped.

**Comment by Mikubill** [comment]
It's OOM issue. Have you tried medvram or lowvram option?

**Comment by JeffreyBull76** [comment]
I am using lowvram and it worked fine for like a week, I haven't changed my vram capacity

**Comment by JeffreyBull76** [comment]
Did something change with the models that they require more memory now? I have like a whole folder of images generated with it on this exact machine, its just weird its suddenly not working

**Comment by shiningaster** [comment]
I found the problem, it's the last current update, from the scripts/controlnet.py.
Simply change **if issubclass(type(p), StableDiffusionProcessingImg2Img) and p.inpaint_full_res == True:**
Back to this:
**if p.inpaint_full_res == True:**
I was having the same problem until I changed it.
I honestly don't know how this screw things over, but it works.

**Comment by ljleb** [comment]
#183 fixes this as well. I'm merging main into it and testing before updating the remote.

**Comment by ljleb** [comment]
The correct way to implement it might be
```
if getattr(p, 'inpaint_full_res', False):
```
instead maybe? This issubclass test was added to make sure `p` has the member `inpaint_full_res` IIUC.

**Comment by Lexcess** [comment]
> It's OOM issue. Have you tried medvram or lowvram option?

I think there are some weird interactions going on. Possibly related to Depth? Although the log above seemed to a Canny generation. Here are some steps and the outcomes:

1. Generate from Pose - success
2. Generate from Pose with different checkpoint - success
3. Generate from Canny - success
4. Generate from depth - error as above "CUDA out of memory. Tried to allocate 16.00 MiB"
5. Generate from Canny - new error "RuntimeError: Expected all tensors to be on the same device..."
6. Restart and generate from depth - error as above "CUDA out of memory. Tried to allocate 30.00 MiB"

Not sure how to narrow down a repo for you but here is the full log if it helps:

**3. Successful Canny generation**

```PowerShell
restoring last networks
Loading preprocessor: canny, model: control_sd15_CannyDiffV1 [ea6e3b9c]
Loaded state_dict from [C:\Users\USER\repos\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_sd15_CannyDiffV1.safetensors]
Offset cloned: 298 values
ControlNet model control_sd15_CannyDiffV1 [ea6e3b9c] loaded.
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:15<00:00,  1.53s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 10/10 [00:15<00:00,  1.56s/it]
```


**4. Failed Depth generation**

```PowerShell
restoring last networks
Loading preprocessor: depth, model: control_sd15_DepthDiffV1 [978ef0a1]
Loaded state_dict from [C:\Users\USER\repos\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_sd15_DepthDiffV1.safetensors]
Offset cloned: 298 values
ControlNet model control_sd15_DepthDiffV1 [978ef0a1] loaded.
  0%|                                                                                           | 0/10 [00:01<?, ?it/s]
Error completing request
Arguments: ('task(4x8ubng40n67tda)', 'RAW photograph, man with a flower in his hand, in front of a meadow', 'ugly, deformed, cartoon', [], 10, 1, False, False, 1, 1, 5, 55555.0, -1.0, 0, 0, 0, False, 768, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, True, 'depth', 'control_sd15_DepthDiffV1 [978ef0a1]', 1, {'image': array([[[ 85, 160, 252],
        [ 85, 159, 252],
        [ 85, 159, 252],
        ...,
        [ 58, 151, 250],
        [ 58, 151, 250],
        [ 58, 151, 251]],

       [[ 82, 153, 254],
        [ 82, 153, 254],
        [ 82, 153, 254],
        ...,
        [ 56, 142, 254],
        [ 55, 141, 253],
        [ 56, 141, 254]],

       [[ 83, 150, 250],
        [ 83, 150, 250],
        [ 83, 150, 250],
        ...,
        [ 56, 140, 248],
        [ 56, 140, 248],
        [ 56, 140, 248]],

       ...,

       [[ 38,  16,  10],
        [ 38,  23,  26],
        [ 30,  18,  16],
        ...,
        [124,  95,  43],
        [131, 100,  52],
        [135, 100,  51]],

       [[ 44,  26,  18],
        [ 40,  18,  18],
        [ 29,  21,  26],
        ...,
        [112,  84,  44],
        [135,  99,  56],
        [131,  93,  49]],

       [[ 66,  44,  33],
        [ 59,  41,  31],
        [ 49,  35,  24],
        ...,
        [122,  88,  52],
        [140, 102,  66],
        [135, 104,  57]]], dtype=uint8), 'mask': array([[[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       ...,

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]]], dtype=uint8)}, False, 'Scale to Fit (Inner Fit)', False, False, 384, 64, 64, 1, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\processing.py", line 632, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\processing.py", line 832, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 349, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 225, in launch_sampling
    return func()
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 349, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 123, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": [cond_in[a:b]], "c_concat": [image_cond_in[a:b]]})
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1201, in _call_impl
    result = hook(self, input)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\lowvram.py", line 35, in send_me_to_gpu
    module.to(devices.device)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\core\mixins\device_dtype_mixin.py", line 113, in to
    return super().to(*args, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 989, in to
    return self._apply(convert)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 6.00 GiB total capacity; 5.20 GiB already allocated; 0 bytes free; 5.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**5. Attempt to repeat the last successful Canny generation**

```PowerShell
restoring last networks
Loading preprocessor: canny, model: control_sd15_CannyDiffV1 [ea6e3b9c]
Loaded state_dict from [C:\Users\USER\repos\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_sd15_CannyDiffV1.safetensors]
Offset cloned: 298 values
ControlNet model control_sd15_CannyDiffV1 [ea6e3b9c] loaded.
Error completing request
Arguments: ('task(9znmv1o4zkutj3c)', 'RAW photograph, man with a flower in his hand, in front of a meadow', 'ugly, deformed, cartoon', [], 10, 1, False, False, 1, 1, 5, 55555.0, -1.0, 0, 0, 0, False, 768, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, True, 'canny', 'control_sd15_CannyDiffV1 [ea6e3b9c]', 1, {'image': array([[[ 85, 160, 252],
        [ 85, 159, 252],
        [ 85, 159, 252],
        ...,
        [ 58, 151, 250],
        [ 58, 151, 250],
        [ 58, 151, 251]],

       [[ 82, 153, 254],
        [ 82, 153, 254],
        [ 82, 153, 254],
        ...,
        [ 56, 142, 254],
        [ 55, 141, 253],
        [ 56, 141, 254]],

       [[ 83, 150, 250],
        [ 83, 150, 250],
        [ 83, 150, 250],
        ...,
        [ 56, 140, 248],
        [ 56, 140, 248],
        [ 56, 140, 248]],

       ...,

       [[ 38,  16,  10],
        [ 38,  23,  26],
        [ 30,  18,  16],
        ...,
        [124,  95,  43],
        [131, 100,  52],
        [135, 100,  51]],

       [[ 44,  26,  18],
        [ 40,  18,  18],
        [ 29,  21,  26],
        ...,
        [112,  84,  44],
        [135,  99,  56],
        [131,  93,  49]],

       [[ 66,  44,  33],
        [ 59,  41,  31],
        [ 49,  35,  24],
        ...,
        [122,  88,  52],
        [140, 102,  66],
        [135, 104,  57]]], dtype=uint8), 'mask': array([[[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       ...,

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]]], dtype=uint8)}, False, 'Scale to Fit (Inner Fit)', False, False, 512, 100, 200, 1, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\processing.py", line 621, in process_images_inner
    uc = get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, p.steps, cached_uc)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\processing.py", line 570, in get_conds_with_caching
    cache[1] = function(shared.sd_model, required_prompts, steps)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\prompt_parser.py", line 140, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 669, in get_learned_conditioning
    c = self.cond_stage_model(c)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\sd_hijack_clip.py", line 229, in forward
    z = self.process_tokens(tokens, multipliers)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\sd_hijack_clip.py", line 254, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\sd_hijack_clip.py", line 302, in encode_with_transformers
    outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 811, in forward
    return self.text_model(
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 708, in forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 223, in forward
    inputs_embeds = self.token_embedding(input_ids)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\sd_hijack.py", line 222, in forward
    inputs_embeds = self.wrapped(input_ids)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\sparse.py", line 160, in forward
    return F.embedding(
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)
```

**6. Attempting the Depth with fresh instance**

```PowerShell
Loading preprocessor: depth, model: control_sd15_DepthDiffV1 [978ef0a1]
Loaded state_dict from [C:\Users\USER\repos\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_sd15_DepthDiffV1.safetensors]
Offset cloned: 298 values
ControlNet model control_sd15_DepthDiffV1 [978ef0a1] loaded.
  0%|                                                                                           | 0/10 [00:04<?, ?it/s]
Loading weights [1a189f0be6] from C:\Users\USER\repos\stable-diffusion-webui\models\Stable-diffusion\sd-v1-5-pruned.safetensors
Loading VAE weights specified in settings: C:\Users\USER\repos\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying xformers cross attention optimization.
Weights loaded in 1.5s (load weights from disk: 0.6s, apply weights to model: 0.7s, load VAE: 0.2s).
Error completing request
Arguments: ('task(rrrwf1a1o9b0i3v)', 'RAW photograph, man with a flower in his hand, in front of a meadow', 'ugly, deformed, cartoon', [], 10, 1, False, False, 1, 1, 5, 55555.0, -1.0, 0, 0, 0, False, 768, 512, False, 0.7, 2, 'Latent', 0, 0, 0, ['Model hash: 9f1bfee7a0'], 0, True, 'depth', 'control_sd15_DepthDiffV1 [978ef0a1]', 1, {'image': array([[[ 85, 160, 252],
        [ 85, 159, 252],
        [ 85, 159, 252],
        ...,
        [ 58, 151, 250],
        [ 58, 151, 250],
        [ 58, 151, 251]],

       [[ 82, 153, 254],
        [ 82, 153, 254],
        [ 82, 153, 254],
        ...,
        [ 56, 142, 254],
        [ 55, 141, 253],
        [ 56, 141, 254]],

       [[ 83, 150, 250],
        [ 83, 150, 250],
        [ 83, 150, 250],
        ...,
        [ 56, 140, 248],
        [ 56, 140, 248],
        [ 56, 140, 248]],

       ...,

       [[ 38,  16,  10],
        [ 38,  23,  26],
        [ 30,  18,  16],
        ...,
        [124,  95,  43],
        [131, 100,  52],
        [135, 100,  51]],

       [[ 44,  26,  18],
        [ 40,  18,  18],
        [ 29,  21,  26],
        ...,
        [112,  84,  44],
        [135,  99,  56],
        [131,  93,  49]],

       [[ 66,  44,  33],
        [ 59,  41,  31],
        [ 49,  35,  24],
        ...,
        [122,  88,  52],
        [140, 102,  66],
        [135, 104,  57]]], dtype=uint8), 'mask': array([[[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       ...,

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]]], dtype=uint8)}, False, 'Scale to Fit (Inner Fit)', False, False, 384, 64, 64, 1, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\processing.py", line 632, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\processing.py", line 832, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 349, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 225, in launch_sampling
    return func()
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 349, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 123, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": [cond_in[a:b]], "c_concat": [image_cond_in[a:b]]})
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\Users\USER\repos\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 201, in forward2
    return forward(*args, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 150, in forward
    control = outer.control_model(x=x_in, hint=outer.hint_cond, timesteps=timesteps, context=context)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 495, in forward
    h = module(h, emb, context)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 324, in forward
    x = block(x, context=context[i])
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 259, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 114, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 129, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 264, in _forward
    x = self.ff(self.norm3(x)) + x
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 73, in forward
    return self.net(x)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "C:\Users\USER\repos\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\repos\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 53, in forward
    return x * F.gelu(gate)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 30.00 MiB (GPU 0; 6.00 GiB total capacity; 5.20 GiB already allocated; 0 bytes free; 5.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by JeffreyBull76** [comment]
@Lexcess Yes that is pretty much what I have happening. It works to a point then fails a particular generation then just catches itself in a loop and ceases to work until you restart the webui. @shiningaster  & @ljleb thanks I'll try both solutions later and let you know. I'm going to reinstall Pytorch as well (not sure if that was really affecting anything but it might)

**Comment by JeffreyBull76** [comment]
So I reinstalled pytorch on Cuda and then downloaded the most up to date models (mine were a version behind) I then double checked and my bad I was running in medvram (although it had worked in medvram before when the repo was first released) I have 6gb vram so its borderline for me.

Anyway I swapped it out to lowvram and the depthmap generation works fine. Tried it back on medvram and it crashed again same error, so it is that which is causing the issue (maybe changes in the models make them harder to run on low gpu's?) the only weird thing is once it bugs out it literally gimps my webui session and it needs restarting. So its definitely part my user error but also some sort of weird interaction going on (its as @Lexcess said)

All that said hopefully this is of some use to those working on controlNet and massive thanks for your work so far its an awesome project ! If you need any more data regarding the error feel free to message me, I'll close this out now and thanks again all.

**Comment by Alwaysfindtheway** [comment]
II struggled with this problem for two days, and solved it in a ridiculously simple way: delete my configs for WebUI.

I uninstalled and reinstalled Controlnet countless times over the course of those two days, but nothing worked. 

This morning, I was in the shower when it suddenly came to me that a configuration file in the WebUI on the RunPod, that I had set incorrectly a long time ago, was causing the problem of not being able to generate any images. 

I immediately shut down the WebUI, deleted all of its configuration files, config.json and ui-config.json, along with Controlnet, then turned the WebUI back on and reinstalled Controlnet.

Boom, it was fixed right away. Hopefully this comment will be a solution for someone suffering from the same problem as me.
